---
- name: sdasdsadsa
  ansible.builtin.set_fact:
    nfc_test_plays: {}

- name: Merge Artifacts
  ansible.builtin.include_vars:
    # name: combined
    file: "{{ (test_root_dir | string) }}/artifacts/{{ item.path }}"
    hash_behaviour: merge
    # ignore_unknown_extensions: true
    # extensions:
    #   - yaml
  with_filetree: "{{ (test_root_dir | string) }}/artifacts/"
  delegate_facts: true
  delegate_to: localhost
  run_once: true


- name: TRACE - Combined
  ansible.builtin.debug:
    msg: "{{ nfc_test_plays }}"
  delegate_to: localhost
  run_once: true

- name: Count Failed Tests
  ansible.builtin.include_tasks:
    file: report/failed_tests.yaml 
  loop: "{{ test_results | dict2items }}"
  loop_control:
    loop_var: test_suite_results


- name: Count passed Tests
  ansible.builtin.include_tasks:
    file: report/passed_tests.yaml 
  loop: "{{ test_results | dict2items }}"
  loop_control:
    loop_var: test_suite_results


- name: Create XUnit Test Report
  ansible.builtin.template:
    src: xunit.xml.j2
    dest: "{{ (test_root_dir | string) + '/Unit_Test.junit.xml' }}"
    mode: '755'


# - name: B
#   ansible.builtin.file:
#     con
